# ASP.NET Core
# Build and test ASP.NET Core projects targeting .NET Core.
# Add steps that run tests, create a NuGet package, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/dotnet-core

trigger: none
# - master

variables:
  buildConfiguration: 'Release'
  appName: 'hello-world-pipeline'
  cronExpression: '* * * * */5'

pool:
  vmImage: ubuntu-latest

steps:
- task: Bash@3
  displayName: 'Execute Bash Commands'
  inputs:
    targetType: 'inline'
    script: |
      # Write your commands here
      echo 'Running $(appName) from Task Assistant .NET $(cronExpression)'

- script: dotnet build --configuration $(buildConfiguration)
  displayName: 'Build with Release Config'

  
